# ***DATA PREPROCESSING***
> ***Our main aim in this project is to load in the data and preprocess it for the NLP task. We will start with a relatively smaller dataset and transform it. But then copying the blueprint or the methodology we will create a helper function that let's us combine and transform any dataset. This will be useful when we load in a lots of data in future***

`LEARNING AIMS - `
* Learn basic text preprocessing for NLP tasks.
* Learn different concepts such as bagging / stemming / tokenization etc.
* Learn different text methods

In [91]:
import numpy as np
import pandas as pd

In [92]:
## Loading the datasets
train_data = pd.read_csv("train.csv", encoding='unicode_escape')
test_data = pd.read_csv("test.csv", encoding='unicode_escape')

In [93]:
train_data.head()

,textID,text,selected_text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,morning,0-20,Afghanistan,38928346,652860.0,60
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative,noon,21-30,Albania,2877797,27400.0,105
2,088c60f138,my boss is bullying me...,bullying me,negative,night,31-45,Algeria,43851044,2381740.0,18
3,9642c003ef,what interview! leave me alone,leave me alone,negative,morning,46-60,Andorra,77265,470.0,164
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative,noon,60-70,Angola,32866272,1246700.0,26

In [94]:
test_data.head()

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0

`KEEPING ONLY THE TEXT AND SENTIMENT COLUMN`
> For our helper function we will do the same. We need to ensure that the data that goes into it is in form [text, label] with these as column names

In [95]:
train_data = train_data[["text", "sentiment"]]
test_data = test_data[["text", "sentiment"]]
train_data.rename(columns={'sentiment': 'label'}, inplace=True)
test_data.rename(columns={'sentiment':'label'}, inplace=True)
train_data.head()

                                                text     label
0                I`d have responded, if I were going   neutral
1      Sooo SAD I will miss you here in San Diego!!!  negative
2                          my boss is bullying me...  negative
3                     what interview! leave me alone  negative
4   Sons of ****, why couldn`t they put them on t...  negative

In [96]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    27480 non-null  object
 1   label   27481 non-null  object
dtypes: object(2)
memory usage: 429.5+ KB

In [97]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4815 entries, 0 to 4814
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    3534 non-null   object
 1   label   3534 non-null   object
dtypes: object(2)
memory usage: 75.4+ KB

In [98]:
train_data["label"].value_counts()

label
neutral     11118
positive     8582
negative     7781
Name: count, dtype: int64

In [99]:
# CONVERTING LABEL TO NUMERIC
def encode_labels(value):
    priority = {
        "positive": 1,
        "neutral": 0,
        "negative": -1
    }
    if pd.isna(value):
        return None
    return priority.get(value, None)


train_data["label"] = train_data["label"].apply(encode_labels)
test_data["label"] = test_data["label"].apply(encode_labels)

In [100]:
test_data.head()

                                                text  label
0  Last session of the day  http://twitpic.com/67ezh    0.0
1   Shanghai is also really exciting (precisely -...    1.0
2  Recession hit Veronique Branquinho, she has to...   -1.0
3                                        happy bday!    1.0
4             http://twitpic.com/4w75p - I like it!!    1.0

In [101]:
test_data["label"].value_counts()

label
 0.0    1430
 1.0    1103
-1.0    1001
Name: count, dtype: int64

In [102]:
### ***LET'S VISUALIZE SOME DATA SAMPLES***
priority = {
        1: "positive",
        0: "neutral",
        -1: "negative"
    }
def samples(label=1, n=10):
  samples = train_data[train_data["label"] == label]
  samples_shuffled = samples.sample(frac=1).reset_index(drop = True)
  samples_n = list(samples_shuffled["text"].iloc[:n])

  print("---------------------------------------")
  print(priority[label].upper())
  print("---------------------------------------")

  for index, sample in enumerate(samples_n):
    print(f"SAMPLE {index + 1} : {sample}")
    print(" ")

samples(label=-1)

---------------------------------------
NEGATIVE
---------------------------------------
SAMPLE 1 : Not feeling too good at ALL, about to head to work from 12-5.  Not a bad shift, just not fun when you don`t feel well! Hope it goes FAST

SAMPLE 2 : Still unbelievably shocked about the firing of THE best radio personality, Martin Streek

SAMPLE 3 : to be really really... not bored but bad, i won`t now the news  but thats ok. BRB x

SAMPLE 4 :  lame. you should have said hello!

SAMPLE 5 : no class the next two days...but work  everyday from today til next wednesday  so sad

SAMPLE 6 : Is upset that he didn`t get his 24 fix tonight

SAMPLE 7 : I hate TweetDeck when it reaches access limits

SAMPLE 8 : ugh, i dont feel like going to work today

SAMPLE 9 : doesn`t know what to do this evening & is D R E A D I N G work tomorrow  it sucks.

SAMPLE 10 :  aww  i guess not that many people are online though...

## ***DATA PREPROCESSING***
**Now we will basically clean the data and convert them into some useful form to feed to the model**

`THE MAIN STEPS ARE`
* DATA CLEANING
* TOKENIZATION
* STOPWORD REMOVAL
* STEMMING / LEMMATIZATION

In [103]:
# Drop rows with NaN in the 'text' column
train_data = train_data.dropna(subset=["text"]).reset_index(drop=True)
test_data = test_data.dropna(subset=["text"]).reset_index(drop=True)

In [104]:
# 1. converting to lowercase
# 2. removing non letters (doesnt add any information)
# 3. removing non whitespaces (last 2 points is basically keeping letters + whitespaces)
def preprocess1(val):
  str = ""
  for v in val:
    if v.isalnum() or v == ' ':
      str += v
  return str

train_data["text"] = train_data["text"].apply(preprocess1)
test_data["text"] = test_data["text"].apply(preprocess1)

In [105]:
samples()

---------------------------------------
POSITIVE
---------------------------------------
SAMPLE 1 :  That is the best sticker EVER Also I dig your hair Its gotten long since Ive seen you last

SAMPLE 2 : I love my puppy

SAMPLE 3 : thanks 2 become my friendtwitter  selalu ada ruang untuk sahabat

SAMPLE 4 :  Made so many new friends on Twitter around USA Another bike across USA trip would be amazing to see people

SAMPLE 5 :  Thabks This made me feel very special

SAMPLE 6 :  Yesmet Jon last yr at an interesting Questionning Agile Agile 2008 session  Dont see him on this yrs schedule

SAMPLE 7 :  I love catching people singing in their cars Even better if theyre dancing

SAMPLE 8 : had a awesome day

SAMPLE 9 :  coool thanks a lot

SAMPLE 10 : Dear God please let me wake up before 1145 AM tomorrow lol Got plans  Tonight was lets pick on Hero night grow up get a job etc lolz

In [106]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [107]:
## 2. TOKENIZATION
from nltk.tokenize import word_tokenize
def tokenize(val):
  return word_tokenize(val)

train_data["text"] = train_data["text"].apply(tokenize)
test_data["text"] = test_data["text"].apply(tokenize)

In [108]:
train_data.head()

                                                text  label
0          [Id, have, responded, if, I, were, going]      0
1  [Sooo, SAD, I, will, miss, you, here, in, San,...     -1
2                       [my, boss, is, bullying, me]     -1
3                [what, interview, leave, me, alone]     -1
4  [Sons, of, why, couldnt, they, put, them, on, ...     -1

In [109]:
## 3. STOPWORD REMOVAL
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
list(stop_words)[:5]

['ma', 'whom', 'above', 'against', 'about']

In [110]:
stop_words = list(stop_words)
def remove_stopwords(val):
    return [word for word in val if word not in stop_words]

train_data["text"] = train_data["text"].apply(remove_stopwords)
test_data["text"] = test_data["text"].apply(remove_stopwords)

In [111]:
train_data.head(5)

                                              text  label
0                        [Id, responded, I, going]      0
1                 [Sooo, SAD, I, miss, San, Diego]     -1
2                                 [boss, bullying]     -1
3                        [interview, leave, alone]     -1
4  [Sons, couldnt, put, releases, already, bought]     -1

In [112]:
## 4. STEMMING - PORTER STEMMING
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
def stem_words(val):
  stemmed = [stemmer.stem(word) for word in val]
  return stemmed

train_data["text"] = train_data["text"].apply(stem_words)
test_data["text"] = test_data["text"].apply(stem_words)

In [113]:
train_data.head()

                                           text  label
0                          [id, respond, i, go]      0
1              [sooo, sad, i, miss, san, diego]     -1
2                                 [boss, bulli]     -1
3                       [interview, leav, alon]     -1
4  [son, couldnt, put, releas, alreadi, bought]     -1

In [114]:
data = pd.concat([train_data, test_data], axis=0).reset_index(drop=True)
len(data)

31014

In [115]:
## 1. BAG OR WORDS
from sklearn.feature_extraction.text import CountVectorizer

data_text = [''.join(tokens) for tokens in data['text']]

# Fit on full dataset
vectorizer = CountVectorizer(max_features=10000)
X = vectorizer.fit_transform(data_text)
X[:5].toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [116]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Join tokens
data_text = [' '.join(tokens) for tokens in data["text"]]

# Fit vectorizer
vectorizer = CountVectorizer(max_features=10000)
X = vectorizer.fit_transform(data_text)

# Convert sparse matrix to DataFrame
data_bow = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)
data_bow["label"] = data["label"].values

data_bow.head()

,000,007,01,01xx,024,03,04,0405,0407,04071991,...,ãââ½neleg,ãââ½net,ãââ½stupidityãââ½,ãââ½tearãââ½,ãââ½timo,ãââ½ureo,ãââ½whi,ãââ½whyyi,ãââ½you,ãââ½ãââ½
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [117]:
from sklearn.decomposition import TruncatedSVD

# Suppose X is your sparse TF-IDF/BoW matrix
svd = TruncatedSVD(n_components=300, random_state=42)
data_bow_pca = svd.fit_transform(X)

print(X.shape)       # (num_samples, vocab_size)
print(data_bow_pca.shape)  # (num_samples, 300)

(31014, 10000)
(31014, 300)

In [118]:
data_bow_pca

array([[ 3.62169784e-01, -1.26243852e-01, -5.32100102e-01, ...,
         9.35183479e-03,  3.82990887e-02, -1.47538589e-02],
       [ 1.26916943e-01, -2.87872750e-02, -3.72694744e-03, ...,
         1.86071364e-02, -6.45320457e-02,  4.23014813e-02],
       [ 2.37705039e-03,  3.99219530e-04, -1.36884953e-03, ...,
        -2.27469482e-04, -7.49052764e-03, -6.96291883e-04],
       ...,
       [ 2.57657178e-01, -4.17474765e-02, -1.85114459e-01, ...,
        -5.38969481e-02,  1.88201485e-02,  9.03562698e-02],
       [ 3.17099145e-01,  8.77549007e-03, -8.26145545e-02, ...,
         2.04067203e-01, -6.64355985e-02, -1.17156929e-01],
       [ 6.91816774e-03,  1.94703368e-03, -3.34052790e-03, ...,
         5.91603628e-03,  5.71285558e-02,  4.15688112e-02]])

In [119]:
columns = [f"pc{i+1}" for i in range(data_bow_pca.shape[1])]

df_bow_pca = pd.DataFrame(data_bow_pca, columns=columns)
df_bow_pca.head()

,pc1,pc2,pc3,pc4,pc5,pc6,pc7,pc8,pc9,pc10,...,pc291,pc292,pc293,pc294,pc295,pc296,pc297,pc298,pc299,pc300
0,0.362170,-0.126244,-0.532100,0.718686,-0.061814,-0.013964,-0.073069,0.016825,-0.020079,0.113715,...,0.035147,-0.064252,0.018195,-0.008074,-0.025719,-0.030722,-0.035145,0.009352,0.038299,-0.014754
1,0.126917,-0.028787,-0.003727,-0.035528,-0.060249,-0.056406,0.023458,0.026130,0.038796,-0.113168,...,0.018496,0.018876,0.070654,0.018654,0.029565,0.070535,-0.027509,0.018607,-0.064532,0.042301
2,0.002377,0.000399,-0.001369,-0.000884,-0.001185,0.000413,0.003273,-0.001826,-0.000639,0.000152,...,-0.001493,0.004375,-0.002063,-0.003601,-0.002861,-0.005095,0.001249,-0.000227,-0.007491,-0.000696
3,0.024040,-0.003904,-0.011361,-0.007145,-0.001371,0.001160,0.011826,0.001887,-0.006461,-0.017157,...,-0.001009,-0.001262,0.032586,0.019319,-0.004700,-0.006274,-0.001289,-0.005702,-0.008512,0.001618
4,0.046941,0.001856,-0.018844,-0.031515,-0.011753,-0.001519,0.005129,0.006778,0.022602,-0.025209,...,-0.015115,0.013738,0.012291,0.029881,-0.026108,-0.075190,-0.035548,0.154193,-0.071550,-0.045380

In [120]:
df_bow_pca["label"] = data["label"].values
df_bow_pca["label"]

0        0.0
1       -1.0
2       -1.0
3       -1.0
4       -1.0
        ...
31009   -1.0
31010    1.0
31011   -1.0
31012    1.0
31013    1.0
Name: label, Length: 31014, dtype: float64

In [122]:
data_bow.to_csv("data_bow.csv")
df_bow_pca.to_csv("data_bow_pca.csv")